# Check a waypoint against the current octomap
# author: Edith Langer, langer@acin.tuwien.ac.at

# a view cones that was not visited yet
geometry_msgs/Pose waypoint
float32 fov
float32 viewing_distance

---
#True if we want to explore it, false otherwise.
std_msgs/Bool explore_waypoint  
