# Child following action definition
# author: Markus Bajones (bajo), bajones@acin.tuwien.ac.at

std_msgs/String child_id_to_follow
geometry_msgs/Point[] target_locations # If the child gets close to any these locations, stop.
float32 time_standing_still # If the child stands still for this many seconds, stop.
---
geometry_msgs/PoseStamped final_location # Although this can be retrieved from the KnowledgeBase
---
# No feedback.
