string frame_id
float64[] positions
bool check_octomap_collision
bool check_self_collision
float64 max_planning_time
bool fold_arm
float64 min_distance_before_folding
---
int32 SUCCESS=0
int32 WRONG_ARRAY_DIMENSION=1
int32 NO_OCTOMAP_AVAILABLE=2
int32 INVALID_END_EFFECTOR_POSE=3
int32 COLLISION_GOAL_POSE=4
int32 COLLISION_FOLDING=5
int32 ERROR_2DOF_PLANNING=6
int32 ERROR_8DOF_PLANNING=7

int32 result
