# Robot expressions
# These can be epxressed via sound (beep), head movements (nod), body movements (wiggle)
# The expression message itself is just a regular string, but only the constants
# below should be used!
#
# Michael Zillich, April 2016

# complete list of all expressions that the robot can display
# hello, as greeting
string HELLO = HELLO
# ok, acknowledge
string OK = OK
# yes, as an answer to a polar question
string YES = YES
# no, as an answer to a polar question
string NO = NO
# look here, here! trying to grab the user's attention
string HERE_HERE = HERE_HERE
# something went wrong, expressing distress
string OH_NO = OH_NO
# something succeeded, expressing happiness
string YEAH = YEAH
# something unexpected just happened
string SURPRISE = SURPRISE
# whaat? something is unclear, tell me more
string WHAT = WHAT

