# Manipulation action messages: MANIPULATION

# goal definition
string manipulation_type
string object_id
geometry_msgs/PoseStamped pose
squirrel_object_perception_msgs/BCylinder object_bounding_cylinder
float64[] joints
---
# result definition
string result_status
float32 stability
---
#feedback
string current_phase
string current_status
int32 percent_completed
